spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fantasy_db
    #username: ${DB_USERNAME}
    #password: ${DB_PASSWORD}
    username: fantasy_root_user
    password: Hamma92927990
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration
    out-of-order: true
#    clean-disabled: false

  cache:
    type: caffeine

  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false # Disable automatic job execution at startup

application:
  name: Fantasy League Backend
  mail:
    from: no-reply@fantasyapp.com
    host: smtp.example.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}

server:
  port: 8080

logging:
  level:
    root: INFO
    com.example.fantasy: DEBUG

external:
  fixture:
    api:
      url: https://api.example.com/fixtures
      #key: ${FIXTURE_API_KEY}
      key: xxx
#  player:
#    api:
#      url: https://api.example.com/players
#      key: ${PLAYER_API_KEY}
#  team:
#    api:
#      url: https://api.example.com/teams
#      key: ${TEAM_API_KEY}
